name: 'Milestone Release Action'
description: 'Creates a Release with a changelog from a Milestone'
branding:
  icon: package
  color: red
inputs:
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    default: ${{github.token}}
    required: true
  milestone-title:
    description: 'The milestone to release'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
