name: 'Milestone Release Action'
description: 'Creates a Release with a changelog from a Milestone'
branding:
  icon: package
  color: red
inputs:
  github-token:
    description: 'The GitHub token used to create an authenticated client'
    default: ${{github.token}}
    required: true
  milestone-title:
    description: 'The milestone to release'
    required: true
  milestone-next:
    description: 'The next milestone'
    required: false
  pre-body:
    description: 'Body content above the changelog'
    required: false
  post-body:
    description: 'Body content below the changelog'
    required: false
  draft:
    description: 'Draft flag of the release'
    required: false
  prerelease:
    description: 'Pre-release flag of the release'
    required: false
  files:
    description: 'Comma-separated list of release assets to upload'
    required: false
    
runs:
  using: 'node20'
  main: 'index.js'
